### ISSUE TITLE
手机浏览器打开播放事件一直是00.00

### ISSUE THREAD

**Issue by lankongmoxing** [IFmiss/wx-audio#1]
不支持手机浏览器环境吗

**Comment by AnglerDW** [comment]
@lankongmoxing 你好请问是什么地方显示00:00，音乐是需要加载的，在获取到元数据之前就是00：00，你看音频是否可播放，播放的话时间是否还是00：00

**Comment by lankongmoxing** [comment]
是你们自己的demo

**Comment by lankongmoxing** [comment]
http://www.daiwei.org/components/wx-audio/html/audio.html

**Comment by AnglerDW** [comment]
我试了 我在ios下试了没什么问题，ios上好像是音乐必须完全加载 或者加载达到一定程度之后才会播放，如果播放的话，不存在00：00的状况，你那个是什么问题   能说的具体一点吗

**Comment by lankongmoxing** [comment]
小米6和魅族我这里试了不行，vivo是可以的。就是音频时长是00:00。可以加q。439891354.。。。

**Comment by AnglerDW** [comment]
你加我吧  加不了你  185098535

**Comment by lankongmoxing** [comment]
你再试试，你的也要名字验证。我刚刚去掉了
