### ISSUE TITLE
这个插件ios上也没法边放边播

### ISSUE THREAD

**Issue by chenendian** [IFmiss/wx-audio#2]

**Comment by AnglerDW** [comment]
能否详细描述一下 以及手机的型号和版本号

**Comment by chenendian** [comment]
我想表达的是，必须点击后音频才开始缓存，然后我们的音频比较大，大概10几分钟，需要等待好几秒才开始播放  这个不是这个插件的问题，用原声的也有这个bug，  查过了 是因为ios必须要用户手动触发，我以为这个插件可以没点击之前就能缓存呢，，，不知道你有好的解决办法没有？

**Comment by AnglerDW** [comment]
确实是这样的
ios 确实是要等缓存到一定程度才能播放
可以从音频方面去入手，cdn，或者缩小音频的大小

**Comment by chenendian** [comment]
非常感谢，暂时采取的办法是缩小音频，想知道有类似video.js类似的那种插件吗，就是变缓存边播放的，找了很久一直没找到，

**Comment by AnglerDW** [comment]
这个确实是不太清楚啊，可以找找，解决方法总是有的

**Comment by chenendian** [comment]
谢啦   希望能找到吧
